export type SwissPostalLocation = {
  zip: string;
  name: string;
  canton: string;
};

export const SWISS_POSTAL_LOCATIONS: SwissPostalLocation[] = [
  // Grössere Schweizer Städte / Orte mit Haupt-PLZ
  { zip: "1201", name: "Genf", canton: "GE" },
  { zip: "4051", name: "Basel", canton: "BS" },
  { zip: "1003", name: "Lausanne", canton: "VD" },
  { zip: "3011", name: "Bern", canton: "BE" },
  { zip: "6003", name: "Luzern", canton: "LU" },
  { zip: "9000", name: "St. Gallen", canton: "SG" },
  { zip: "6900", name: "Lugano", canton: "TI" },
  { zip: "2502", name: "Biel/Bienne", canton: "BE" },
  { zip: "3600", name: "Thun", canton: "BE" },
  { zip: "3098", name: "Köniz", canton: "BE" },
  { zip: "2300", name: "La Chaux-de-Fonds", canton: "NE" },
  { zip: "8200", name: "Schaffhausen", canton: "SH" },
  { zip: "1700", name: "Fribourg", canton: "FR" },
  { zip: "7000", name: "Chur", canton: "GR" },
  { zip: "1214", name: "Vernier", canton: "GE" },
  { zip: "2000", name: "Neuchâtel", canton: "NE" },
  { zip: "1950", name: "Sion", canton: "VS" },
  { zip: "1212", name: "Lancy", canton: "GE" },
  { zip: "6032", name: "Emmen", canton: "LU" },
  { zip: "8640", name: "Rapperswil-Jona", canton: "SG" },
  { zip: "1400", name: "Yverdon-les-Bains", canton: "VD" },
  { zip: "6300", name: "Zug", canton: "ZG" },
  { zip: "6010", name: "Kriens", canton: "LU" },
  { zip: "1820", name: "Montreux", canton: "VD" },
  { zip: "8500", name: "Frauenfeld", canton: "TG" },
  { zip: "9500", name: "Wil", canton: "SG" },
  { zip: "9200", name: "Gossau", canton: "SG" },
  { zip: "5400", name: "Baden", canton: "AG" },
  { zip: "6500", name: "Bellinzona", canton: "TI" },
  { zip: "5000", name: "Aarau", canton: "AG" },
  { zip: "9100", name: "Herisau", canton: "AR" },
  { zip: "1020", name: "Renens", canton: "VD" },
  { zip: "1260", name: "Nyon", canton: "VD" },
  { zip: "1800", name: "Vevey", canton: "VD" },
  { zip: "1217", name: "Meyrin", canton: "GE" },
  { zip: "1227", name: "Carouge", canton: "GE" },
  { zip: "1630", name: "Bulle", canton: "FR" },
  { zip: "8280", name: "Kreuzlingen", canton: "TG" },
  { zip: "1920", name: "Martigny", canton: "VS" },
  { zip: "4600", name: "Olten", canton: "SO" },
  { zip: "4500", name: "Solothurn", canton: "SO" },
  { zip: "2540", name: "Grenchen", canton: "SO" },
  { zip: "6600", name: "Locarno", canton: "TI" },
  { zip: "4133", name: "Pratteln", canton: "BL" },
  { zip: "4132", name: "Muttenz", canton: "BL" },
  { zip: "1213", name: "Onex", canton: "GE" },
  { zip: "1009", name: "Pully", canton: "VD" },
  { zip: "1196", name: "Gland", canton: "VD" },
  { zip: "7270", name: "Davos", canton: "GR" },
  { zip: "3900", name: "Brig-Glis", canton: "VS" },
  { zip: "1870", name: "Monthey", canton: "VS" },
  { zip: "3076", name: "Worb", canton: "BE" },
  { zip: "3250", name: "Lyss", canton: "BE" },
  { zip: "3400", name: "Burgdorf", canton: "BE" },
  { zip: "4900", name: "Langenthal", canton: "BE" },
  { zip: "3700", name: "Spiez", canton: "BE" },
  { zip: "5610", name: "Wohlen", canton: "AG" },
  { zip: "1110", name: "Morges", canton: "VD" },
  { zip: "5430", name: "Wettingen", canton: "AG" },
  { zip: "8957", name: "Spreitenbach", canton: "AG" },
  { zip: "4310", name: "Rheinfelden", canton: "AG" },
  { zip: "4123", name: "Allschwil", canton: "BL" },
  { zip: "4410", name: "Liestal", canton: "BL" },
  { zip: "9320", name: "Arbon", canton: "TG" },
  { zip: "8580", name: "Amriswil", canton: "TG" },
  { zip: "8590", name: "Romanshorn", canton: "TG" },
  { zip: "3960", name: "Sierre", canton: "VS" },
  { zip: "3930", name: "Visp", canton: "VS" },
  { zip: "6210", name: "Sursee", canton: "LU" },
  { zip: "6048", name: "Horw", canton: "LU" },
  { zip: "6030", name: "Ebikon", canton: "LU" },
  { zip: "6340", name: "Baar", canton: "ZG" },
  { zip: "6330", name: "Cham", canton: "ZG" },
  { zip: "6312", name: "Steinhausen", canton: "ZG" },
  { zip: "8807", name: "Freienbach", canton: "SZ" },
  { zip: "8832", name: "Wollerau", canton: "SZ" },
  { zip: "6430", name: "Schwyz", canton: "SZ" },
  { zip: "6460", name: "Altdorf", canton: "UR" },
  { zip: "6060", name: "Sarnen", canton: "OW" },
  { zip: "8750", name: "Glarus", canton: "GL" },
  { zip: "9050", name: "Appenzell", canton: "AI" },
  { zip: "2800", name: "Delémont", canton: "JU" },
  { zip: "2900", name: "Porrentruy", canton: "JU" },
  { zip: "2740", name: "Moutier", canton: "BE" },
  { zip: "9470", name: "Buchs", canton: "SG" },
  { zip: "9240", name: "Uzwil", canton: "SG" },
  { zip: "7320", name: "Sargans", canton: "SG" },
  { zip: "8880", name: "Walenstadt", canton: "SG" },
  { zip: "6830", name: "Chiasso", canton: "TI" },
  { zip: "6850", name: "Mendrisio", canton: "TI" },
  { zip: "6612", name: "Ascona", canton: "TI" },
  { zip: "1530", name: "Payerne", canton: "VD" },
  { zip: "1860", name: "Aigle", canton: "VD" },

  // Kanton Zürich - alle 160 politischen Gemeinden mit Haupt-PLZ
  { zip: "8001", name: "Zürich", canton: "ZH" },
  { zip: "8914", name: "Aeugst am Albis", canton: "ZH" },
  { zip: "8910", name: "Affoltern am Albis", canton: "ZH" },
  { zip: "8906", name: "Bonstetten", canton: "ZH" },
  { zip: "8915", name: "Hausen am Albis", canton: "ZH" },
  { zip: "8908", name: "Hedingen", canton: "ZH" },
  { zip: "8926", name: "Kappel am Albis", canton: "ZH" },
  { zip: "8934", name: "Knonau", canton: "ZH" },
  { zip: "8933", name: "Maschwanden", canton: "ZH" },
  { zip: "8932", name: "Mettmenstetten", canton: "ZH" },
  { zip: "8912", name: "Obfelden", canton: "ZH" },
  { zip: "8913", name: "Ottenbach", canton: "ZH" },
  { zip: "8911", name: "Rifferswil", canton: "ZH" },
  { zip: "8143", name: "Stallikon", canton: "ZH" },
  { zip: "8907", name: "Wettswil am Albis", canton: "ZH" },
  { zip: "8134", name: "Adliswil", canton: "ZH" },
  { zip: "8810", name: "Horgen", canton: "ZH" },
  { zip: "8802", name: "Kilchberg", canton: "ZH" },
  { zip: "8135", name: "Langnau am Albis", canton: "ZH" },
  { zip: "8942", name: "Oberrieden", canton: "ZH" },
  { zip: "8805", name: "Richterswil", canton: "ZH" },
  { zip: "8803", name: "Rüschlikon", canton: "ZH" },
  { zip: "8800", name: "Thalwil", canton: "ZH" },
  { zip: "8820", name: "Wädenswil", canton: "ZH" },
  { zip: "8703", name: "Erlenbach", canton: "ZH" },
  { zip: "8704", name: "Herrliberg", canton: "ZH" },
  { zip: "8634", name: "Hombrechtikon", canton: "ZH" },
  { zip: "8700", name: "Küsnacht", canton: "ZH" },
  { zip: "8708", name: "Männedorf", canton: "ZH" },
  { zip: "8706", name: "Meilen", canton: "ZH" },
  { zip: "8618", name: "Oetwil am See", canton: "ZH" },
  { zip: "8712", name: "Stäfa", canton: "ZH" },
  { zip: "8707", name: "Uetikon am See", canton: "ZH" },
  { zip: "8702", name: "Zollikon", canton: "ZH" },
  { zip: "8126", name: "Zumikon", canton: "ZH" },
  { zip: "8344", name: "Bäretswil", canton: "ZH" },
  { zip: "8608", name: "Bubikon", canton: "ZH" },
  { zip: "8635", name: "Dürnten", canton: "ZH" },
  { zip: "8497", name: "Fischenthal", canton: "ZH" },
  { zip: "8625", name: "Gossau", canton: "ZH" },
  { zip: "8627", name: "Grüningen", canton: "ZH" },
  { zip: "8340", name: "Hinwil", canton: "ZH" },
  { zip: "8630", name: "Rüti", canton: "ZH" },
  { zip: "8607", name: "Seegräben", canton: "ZH" },
  { zip: "8636", name: "Wald", canton: "ZH" },
  { zip: "8620", name: "Wetzikon", canton: "ZH" },
  { zip: "8600", name: "Dübendorf", canton: "ZH" },
  { zip: "8132", name: "Egg", canton: "ZH" },
  { zip: "8117", name: "Fällanden", canton: "ZH" },
  { zip: "8606", name: "Greifensee", canton: "ZH" },
  { zip: "8124", name: "Maur", canton: "ZH" },
  { zip: "8617", name: "Mönchaltorf", canton: "ZH" },
  { zip: "8603", name: "Schwerzenbach", canton: "ZH" },
  { zip: "8610", name: "Uster", canton: "ZH" },
  { zip: "8604", name: "Volketswil", canton: "ZH" },
  { zip: "8602", name: "Wangen-Brüttisellen", canton: "ZH" },
  { zip: "8494", name: "Bauma", canton: "ZH" },
  { zip: "8320", name: "Fehraltorf", canton: "ZH" },
  { zip: "8335", name: "Hittnau", canton: "ZH" },
  { zip: "8307", name: "Illnau-Effretikon", canton: "ZH" },
  { zip: "8315", name: "Lindau", canton: "ZH" },
  { zip: "8330", name: "Pfäffikon", canton: "ZH" },
  { zip: "8332", name: "Russikon", canton: "ZH" },
  { zip: "8484", name: "Weisslingen", canton: "ZH" },
  { zip: "8492", name: "Wila", canton: "ZH" },
  { zip: "8489", name: "Wildberg", canton: "ZH" },
  { zip: "8479", name: "Altikon", canton: "ZH" },
  { zip: "8311", name: "Brütten", canton: "ZH" },
  { zip: "8471", name: "Dägerlen", canton: "ZH" },
  { zip: "8421", name: "Dättlikon", canton: "ZH" },
  { zip: "8474", name: "Dinhard", canton: "ZH" },
  { zip: "8353", name: "Elgg", canton: "ZH" },
  { zip: "8548", name: "Ellikon an der Thur", canton: "ZH" },
  { zip: "8352", name: "Elsau", canton: "ZH" },
  { zip: "8523", name: "Hagenbuch", canton: "ZH" },
  { zip: "8442", name: "Hettlingen", canton: "ZH" },
  { zip: "8413", name: "Neftenbach", canton: "ZH" },
  { zip: "8422", name: "Pfungen", canton: "ZH" },
  { zip: "8545", name: "Rickenbach", canton: "ZH" },
  { zip: "8418", name: "Schlatt", canton: "ZH" },
  { zip: "8472", name: "Seuzach", canton: "ZH" },
  { zip: "8488", name: "Turbenthal", canton: "ZH" },
  { zip: "8542", name: "Wiesendangen", canton: "ZH" },
  { zip: "8400", name: "Winterthur", canton: "ZH" },
  { zip: "8487", name: "Zell", canton: "ZH" },
  { zip: "8450", name: "Andelfingen", canton: "ZH" },
  { zip: "8463", name: "Benken", canton: "ZH" },
  { zip: "8415", name: "Berg am Irchel", canton: "ZH" },
  { zip: "8414", name: "Buch am Irchel", canton: "ZH" },
  { zip: "8447", name: "Dachsen", canton: "ZH" },
  { zip: "8458", name: "Dorf", canton: "ZH" },
  { zip: "8245", name: "Feuerthalen", canton: "ZH" },
  { zip: "8416", name: "Flaach", canton: "ZH" },
  { zip: "8247", name: "Flurlingen", canton: "ZH" },
  { zip: "8444", name: "Henggart", canton: "ZH" },
  { zip: "8451", name: "Kleinandelfingen", canton: "ZH" },
  { zip: "8248", name: "Laufen-Uhwiesen", canton: "ZH" },
  { zip: "8460", name: "Marthalen", canton: "ZH" },
  { zip: "8475", name: "Ossingen", canton: "ZH" },
  { zip: "8462", name: "Rheinau", canton: "ZH" },
  { zip: "8477", name: "Stammheim", canton: "ZH" },
  { zip: "8478", name: "Thalheim an der Thur", canton: "ZH" },
  { zip: "8466", name: "Trüllikon", canton: "ZH" },
  { zip: "8467", name: "Truttikon", canton: "ZH" },
  { zip: "8459", name: "Volken", canton: "ZH" },
  { zip: "8184", name: "Bachenbülach", canton: "ZH" },
  { zip: "8303", name: "Bassersdorf", canton: "ZH" },
  { zip: "8180", name: "Bülach", canton: "ZH" },
  { zip: "8305", name: "Dietlikon", canton: "ZH" },
  { zip: "8193", name: "Eglisau", canton: "ZH" },
  { zip: "8424", name: "Embrach", canton: "ZH" },
  { zip: "8427", name: "Freienstein-Teufen", canton: "ZH" },
  { zip: "8192", name: "Glattfelden", canton: "ZH" },
  { zip: "8182", name: "Hochfelden", canton: "ZH" },
  { zip: "8181", name: "Höri", canton: "ZH" },
  { zip: "8194", name: "Hüntwangen", canton: "ZH" },
  { zip: "8302", name: "Kloten", canton: "ZH" },
  { zip: "8426", name: "Lufingen", canton: "ZH" },
  { zip: "8309", name: "Nürensdorf", canton: "ZH" },
  { zip: "8425", name: "Oberembrach", canton: "ZH" },
  { zip: "8152", name: "Opfikon", canton: "ZH" },
  { zip: "8197", name: "Rafz", canton: "ZH" },
  { zip: "8427", name: "Rorbas", canton: "ZH" },
  { zip: "8304", name: "Wallisellen", canton: "ZH" },
  { zip: "8195", name: "Wasterkingen", canton: "ZH" },
  { zip: "8196", name: "Wil", canton: "ZH" },
  { zip: "8185", name: "Winkel", canton: "ZH" },
  { zip: "8164", name: "Bachs", canton: "ZH" },
  { zip: "8113", name: "Boppelsen", canton: "ZH" },
  { zip: "8107", name: "Buchs", canton: "ZH" },
  { zip: "8108", name: "Dällikon", canton: "ZH" },
  { zip: "8114", name: "Dänikon", canton: "ZH" },
  { zip: "8157", name: "Dielsdorf", canton: "ZH" },
  { zip: "8115", name: "Hüttikon", canton: "ZH" },
  { zip: "8173", name: "Neerach", canton: "ZH" },
  { zip: "8172", name: "Niederglatt", canton: "ZH" },
  { zip: "8155", name: "Niederhasli", canton: "ZH" },
  { zip: "8166", name: "Niederweningen", canton: "ZH" },
  { zip: "8154", name: "Oberglatt", canton: "ZH" },
  { zip: "8165", name: "Oberweningen", canton: "ZH" },
  { zip: "8112", name: "Otelfingen", canton: "ZH" },
  { zip: "8158", name: "Regensberg", canton: "ZH" },
  { zip: "8105", name: "Regensdorf", canton: "ZH" },
  { zip: "8153", name: "Rümlang", canton: "ZH" },
  { zip: "8165", name: "Schleinikon", canton: "ZH" },
  { zip: "8165", name: "Schöfflisdorf", canton: "ZH" },
  { zip: "8174", name: "Stadel", canton: "ZH" },
  { zip: "8162", name: "Steinmaur", canton: "ZH" },
  { zip: "8187", name: "Weiach", canton: "ZH" },
  { zip: "8904", name: "Aesch", canton: "ZH" },
  { zip: "8903", name: "Birmensdorf", canton: "ZH" },
  { zip: "8953", name: "Dietikon", canton: "ZH" },
  { zip: "8954", name: "Geroldswil", canton: "ZH" },
  { zip: "8102", name: "Oberengstringen", canton: "ZH" },
  { zip: "8955", name: "Oetwil an der Limmat", canton: "ZH" },
  { zip: "8952", name: "Schlieren", canton: "ZH" },
  { zip: "8142", name: "Uitikon", canton: "ZH" },
  { zip: "8103", name: "Unterengstringen", canton: "ZH" },
  { zip: "8902", name: "Urdorf", canton: "ZH" },
  { zip: "8104", name: "Weiningen", canton: "ZH" },
];

export const SWISS_LOCATIONS = Array.from(
  new Set(SWISS_POSTAL_LOCATIONS.map((location) => location.name))
);